name: Peter Wiggers Blog
author: Peter Wiggers
description: Some experiences of a GCP/Kubernetes addict
avatar: /images/avatar.png
url: https://peterwiggers.com
enforce_ssl: https://peterwiggers.com
baseurl: ""
footer-links:
  email: peter@bitlayer.nl
  rss: rss
#disqus:
#google_analytics: tbd
#google_analytics_ga4: tbd

permalink: /:title/
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: expanded # You might prefer to minify using :compressed

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 5
paginate_path: /page:num/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
